### ISSUE TITLE
 requirements.txt does not install

### ISSUE THREAD

**Issue by EinsteinX** [VarunPatelius/Py-iMessenger#1]
ERROR: Command errored out with exit status 1:
     command: /Users//Coding/Python/Py-iMessenger/venv/bin/python3 /Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/tmprywjwsrl
         cwd: /private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-install-hg1hjrad/pyqt5_04e499e7727b4494b9ed90ff046cf404
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-xl07mnsj/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-xl07mnsj/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-xl07mnsj/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 587, in setup
        self.apply_user_defaults(tool)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-install-hg1hjrad/pyqt5_04e499e7727b4494b9ed90ff046cf404/project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-xl07mnsj/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-xl07mnsj/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 234, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-xl07mnsj/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz#sha256=2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.6). Command errored out with exit status 1: /Users//Coding/Python/Py-iMessenger/venv/bin/python3 /Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/tmprywjwsrl Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyQt5==5.15.4 (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6)
ERROR: No matching distribution found for PyQt5==5.15.4

**Comment by VarunPatelius** [comment]
Try using Python 3.9 rather than 3.10, it lacks support for older PyQt5 versions. Let me know how that works out.

**Comment by EinsteinX** [comment]
Hey i tried it, still not working. 

Collecting PyQt5==5.15.4
  Using cached PyQt5-5.15.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users//Coding/Python/Py-iMessenger/venv/bin/python3 /Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/tmpn4w9lgc0
         cwd: /private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-install-blr6imx7/pyqt5_dcc0647900664734b20bfacac8135877
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-vvf_ylgd/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-vvf_ylgd/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-vvf_ylgd/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 587, in setup
        self.apply_user_defaults(tool)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-install-blr6imx7/pyqt5_dcc0647900664734b20bfacac8135877/project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-vvf_ylgd/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-vvf_ylgd/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 234, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/private/var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/pip-build-env-vvf_ylgd/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz#sha256=2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.6). Command errored out with exit status 1: /Users//Coding/Python/Py-iMessenger/venv/bin/python3 /Users//Coding/Python/Py-iMessenger/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/j2/95vbnhpj6v74q8p3t1jrqzxm0000gn/T/tmpn4w9lgc0 Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement PyQt5==5.15.4 (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6)
ERROR: No matching distribution found for PyQt5==5.15.4
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/Users//Coding/Python/Py-iMessenger/venv/bin/python3 -m pip install --upgrade pip' command.
(venv)@-MacBook-Air Py-iMessenger %

**Comment by EinsteinX** [comment]
Just updated to 3.9 same error but says 3.9 now instead of 3.10

**Comment by VarunPatelius** [comment]
When you updated, did you create a new venv and activate it with 3.9 rather than 3.10. Because in your error message, it looks like python3.10 is running.

**Comment by EinsteinX** [comment]
yea I did, sorry I posted the old error message. It gives the same error with version 3.9 just sub out where it says 3.10 to 3.9 and that's the message

**Comment by VarunPatelius** [comment]
In that case, try updating your pip version and then install with version 5.15.3 of PyQt5, you can try with other package versions.

**Comment by EinsteinX** [comment]
Traceback (most recent call last):
  File "/Users//Coding/Python/Py-iMessenger/main.py", line 1, in <module>
    from src.backend.manage import BackendThread    #This imports the backend component of Py-iMessenger
  File "/Users//Coding/Python/Py-iMessenger/src/backend/manage.py", line 8, in <module>
    from user import userModel              #This component deals with loading and saving all user information
  File "/Users//Coding/Python/Py-iMessenger/src/backend/user/userModel.py", line 2, in <module>
    import jsonpickle                                       #jsonpickle is a library that objects to be pickled into a string that is easy to read and save to a string
ModuleNotFoundError: No module named 'jsonpickle'
(venv) -MacBook-Air Py-iMessenger % 

not working

**Comment by VarunPatelius** [comment]
Yeah is this is progress, so go into the requirements.txt file and remove all the PyQt5 lines and, while still with an activated venv, run the dependency download command to get the rest of the requirements (pip3 install -r requirements.txt)

**Comment by EinsteinX** [comment]
Done now what do i do

**Comment by EinsteinX** [comment]
Traceback (most recent call last):
  File "/Users//Coding/Python/Py-iMessenger/main.py", line 1, in <module>
    from src.backend.manage import BackendThread    #This imports the backend component of Py-iMessenger
  File "/Users//Coding/Python/Py-iMessenger/src/backend/manage.py", line 19, in <module>
    databaseController = databaseModel.DatabaseController()
  File "/Users//Coding/Python/Py-iMessenger/src/backend/database/databaseModel.py", line 9, in __init__
    self.conn = sqlite3.connect(DATABASE_PATH, uri=True, check_same_thread=False)   #Connects to the database
sqlite3.OperationalError: unable to open database file
(venv)@-MacBook-Air Py-iMessenger % 

still doesn't work.

**Comment by VarunPatelius** [comment]
Make sure your Terminal has permissions to access files in your /Library folder. Follow the permissions directions in the README. Also make sure you have iMessage setup and running on your computer properly.

**Comment by EinsteinX** [comment]
Traceback (most recent call last):
  File "/Users//Coding/Py-iMessenger/main.py", line 2, in <module>
    from src.frontend.interface import makeApp      #This imports the frontend component of Py-iMessenger
  File "/Users//Coding/Py-iMessenger/src/frontend/interface.py", line 1, in <module>
    from PyQt5.QtWidgets import QApplication, QDialog, QPushButton, QRadioButton, QLCDNumber, QLabel
ModuleNotFoundError: No module named 'PyQt5'
(venv)@-Air Py-iMessenger % 

still no luck

**Comment by VarunPatelius** [comment]
Was the Venv activated? This issue would've popped up earlier. Activate your venv and run pip freeze in your command line to double check you have all the dependencies.
